In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("iris.csv")  
df.drop(['Id'], 1, inplace=True)
#print('Dataset : \n')

In [2]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clf.fit(x_train, y_train)

KNeighborsClassifier()

In [6]:
y_pred = clf.predict(x_test)

In [7]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.1, 1.5, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158

In [9]:
# SepalL = float(input('Enter Sepal Length(cm) : '))
# SepalW = float(input('Enter Sepal Width(cm) : '))
# PetalL = float(input('Enter Petal Length(cm) : '))
# PetalW = float(input('Enter Petal Width(cm) : '))
# print(clf.predict([[SepalL, SepalW, PetalL, PetalW]]))

In [10]:
from tkinter import *
from PIL import *

root = Tk()
root.title("Iris Data Detector")

root.geometry("434x533")
root.minsize(400,500)
root.maxsize(500,600)

root.config(bg='blue')

def Result():
    l=[]
    slval = slvalue.get()
    swval = swvalue.get()
    plval = plvalue.get()
    pwval = pwvalue.get()
    r = clf.predict([[slval, swval, plval, pwval]])
    print(r)
    l.append(r)
    final_text = ""
    for i in range(0, len(l)):
        final_text += l[i]
        if i % 100 == 0 and i != 0:
            final_text += "\n"
    result = Label(root, text=final_text, pady=10, bg='blue', fg='white', font=("", 18))
    result.pack()
    result.place(x=200, y=350)


title = Label(root,text='Iris Data Detection', pady=50, bg='blue', fg='white', font = ("comicsansms", 25, "bold"))
title.pack()

sl=Label(root,text='Enter Sepal Length: ', pady=10, bg='blue', fg='white', font=("", 14))
sw=Label(root,text='Enter Sepal Width: ', pady=10, bg='blue', fg='white', font=("", 14))
pl=Label(root,text='Enter Petal Length: ', pady=10, bg='blue', fg='white', font=("", 14))
pw=Label(root,text='Enter Petal Width: ', pady=10, bg='blue', fg='white', font=("", 14))

sl.pack()
sw.pack()
pl.pack()
pw.pack()

slvalue = DoubleVar()
swvalue = DoubleVar()
plvalue = DoubleVar()
pwvalue = DoubleVar()

slentry = Entry(root,textvariable = slvalue)
swentry = Entry(root,textvariable = swvalue)
plentry = Entry(root,textvariable = plvalue)
pwentry = Entry(root,textvariable = pwvalue)

slentry.pack()
swentry.pack()
plentry.pack()
pwentry.pack()

sl.place(x=55,y=120)
sw.place(x=55,y=160)
pl.place(x=55,y=200)
pw.place(x=55,y=240)

slentry.place(x=190,y=130)
swentry.place(x=190,y=170)
plentry.place(x=190,y=210)
pwentry.place(x=190,y=250)

b = Button(root, text='Submit', font=("", 14), fg='black', command=Result)
b.pack()
b.place(x=170,y=310)

reslt = Label(root, text='Species : ', pady=10, bg='blue', fg='white', font=("", 18))
reslt.pack()
reslt.place(x=115, y=350)

root.mainloop()

['Iris-virginica']
